// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBNz7YL-hejxHuHvReViPPDqZ0NQMOplI',
    appId: '1:865015229843:web:e912c57c64913544ef4c66',
    messagingSenderId: '865015229843',
    projectId: 'batminton-65659',
    authDomain: 'batminton-65659.firebaseapp.com',
    storageBucket: 'batminton-65659.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCE1W6I2F4jnBHVmCghcQqyC-g7o8ZfAnw',
    appId: '1:865015229843:android:c6f3617ca28ee929ef4c66',
    messagingSenderId: '865015229843',
    projectId: 'batminton-65659',
    storageBucket: 'batminton-65659.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcxIfWelrh-qn-3fqr3D0i1M5NPlEkz5Y',
    appId: '1:865015229843:ios:f97ca40d11be4b36ef4c66',
    messagingSenderId: '865015229843',
    projectId: 'batminton-65659',
    storageBucket: 'batminton-65659.firebasestorage.app',
    iosBundleId: 'com.example.batmintonShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcxIfWelrh-qn-3fqr3D0i1M5NPlEkz5Y',
    appId: '1:865015229843:ios:f97ca40d11be4b36ef4c66',
    messagingSenderId: '865015229843',
    projectId: 'batminton-65659',
    storageBucket: 'batminton-65659.firebasestorage.app',
    iosBundleId: 'com.example.batmintonShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBNz7YL-hejxHuHvReViPPDqZ0NQMOplI',
    appId: '1:865015229843:web:44f37271bc0bdea5ef4c66',
    messagingSenderId: '865015229843',
    projectId: 'batminton-65659',
    authDomain: 'batminton-65659.firebaseapp.com',
    storageBucket: 'batminton-65659.firebasestorage.app',
  );
}
